# Generated by Django 6.0 on 2026-05-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='consumo',
            name='suministro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='consumo',
            unique_together={('upload', 'usuario_consume', 'camion', 'suministro', 'fecha')},
        ),
    ]
