# Generated by Django 6.0 on 2026-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consumo_agrega_suministro'),
    ]

    operations = [
        migrations.AddField(
            model_name='sst',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
