# Generated by Django 6.0 on 2026-05-19 22:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inventario_quita_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManoDeObra',
            fields=[
                ('id_mano_de_obra', models.AutoField(primary_key=True, serialize=False)),
                ('partida', models.CharField(max_length=7, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'mano_de_obra',
            },
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id_suministro', models.AutoField(primary_key=True, serialize=False)),
                ('numero_suministro', models.CharField(db_index=True, max_length=20, unique=True)),
                ('medidor', models.CharField(blank=True, max_length=20)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('monto_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('ejecutado', 'Ejecutado'), ('devuelto', 'Devuelto')], default='asignado', max_length=20)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('ejecutado_por', models.CharField(blank=True, max_length=150)),
                ('motivo_devolucion', models.TextField(blank=True)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'suministro',
            },
        ),
        migrations.AlterModelOptions(
            name='detalleinventario',
            options={'ordering': ['material__matricula']},
        ),
        migrations.AddField(
            model_name='sst',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sst',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sst',
            name='monto_sst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='SSTEncargado',
            fields=[
                ('id_sst_encargado', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('encargado', 'Encargado'), ('capataz', 'Capataz')], max_length=20)),
                ('sst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sst_encargados', to='core.sst')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sst_encargados', to='core.usuario')),
            ],
            options={
                'db_table': 'sst_encargado',
                'unique_together': {('sst', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='SSTManoDeObra',
            fields=[
                ('id_sst_mano_de_obra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mano_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sst_mano_de_obra', to='core.manodeobra')),
                ('sst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sst_mano_de_obra', to='core.sst')),
            ],
            options={
                'db_table': 'sst_mano_de_obra',
                'unique_together': {('sst', 'mano_de_obra')},
            },
        ),
        migrations.CreateModel(
            name='SSTSuministro',
            fields=[
                ('id_sst_suministro', models.AutoField(primary_key=True, serialize=False)),
                ('sst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sst_suministros', to='core.sst')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sst_suministros', to='core.suministro')),
            ],
            options={
                'db_table': 'sst_suministro',
                'unique_together': {('sst', 'suministro')},
            },
        ),
    ]
