# Generated by Django 6.0 on 2026-05-20 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_manodeobra_suministro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sstsuministro',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suministros_asignados', to='core.usuario'),
        ),
    ]
