# Generated by Django 6.0 on 2026-05-20 03:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sstsuministro_asignado_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuministroManoDeObra',
            fields=[
                ('id_suministro_mano_de_obra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mano_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suministros', to='core.manodeobra')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mano_de_obra', to='core.suministro')),
            ],
            options={
                'db_table': 'suministro_mano_de_obra',
                'unique_together': {('suministro', 'mano_de_obra')},
            },
        ),
        migrations.DeleteModel(
            name='SSTManoDeObra',
        ),
    ]
