# Generated by Django 6.0 on 2026-05-20 03:29 (reescrita para migración segura)

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrar_actividades(apps, schema_editor):
    """Crea registros Actividad a partir del texto existente en SST y enlaza el FK."""
    SST = apps.get_model('core', 'SST')
    Actividad = apps.get_model('core', 'Actividad')
    for sst in SST.objects.all():
        if sst.actividad:
            act, _ = Actividad.objects.get_or_create(nombre=sst.actividad)
            sst.actividad_fk = act
            sst.save(update_fields=['actividad_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_suministromanodeobra_delete_sstmanodeobra'),
    ]

    operations = [
        # 1. Crear tabla Actividad
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={'db_table': 'actividad'},
        ),

        # 2. Agregar FK nueva (nullable) junto al CharField existente
        migrations.AddField(
            model_name='sst',
            name='actividad_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ssts',
                to='core.actividad',
            ),
        ),

        # 3. Migrar datos: crear Actividad por cada texto único y enlazar FK
        migrations.RunPython(migrar_actividades, reverse_code=migrations.RunPython.noop),

        # 4. Eliminar el CharField original
        migrations.RemoveField(model_name='sst', name='actividad'),

        # 5. Renombrar actividad_fk → actividad
        migrations.RenameField(model_name='sst', old_name='actividad_fk', new_name='actividad'),

        # 6. Resto de modelos nuevos
        migrations.CreateModel(
            name='LiquidacionSuministro',
            fields=[
                ('id_liquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.suministro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.usuario')),
            ],
            options={'db_table': 'liquidacion_suministro'},
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id_tipo_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_trabajo', to='core.actividad')),
            ],
            options={'db_table': 'tipo_trabajo', 'unique_together': {('actividad', 'nombre')}},
        ),
        migrations.CreateModel(
            name='SuministroTipoTrabajo',
            fields=[
                ('id_suministro_tipo_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_trabajo', to='core.suministro')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suministros', to='core.tipotrabajo')),
            ],
            options={'db_table': 'suministro_tipo_trabajo', 'unique_together': {('suministro', 'tipo_trabajo')}},
        ),
        migrations.CreateModel(
            name='TipoTrabajoEjecutado',
            fields=[
                ('id_tipo_trabajo_ejecutado', models.AutoField(primary_key=True, serialize=False)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_ejecutados', to='core.liquidacionsuministro')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecutados', to='core.tipotrabajo')),
            ],
            options={'db_table': 'tipo_trabajo_ejecutado', 'unique_together': {('liquidacion', 'tipo_trabajo')}},
        ),
        migrations.CreateModel(
            name='PartidaEjecutada',
            fields=[
                ('id_partida_ejecutada', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mano_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_ejecutadas', to='core.manodeobra')),
                ('tipo_trabajo_ejecutado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='core.tipotrabajoejecutado')),
            ],
            options={'db_table': 'partida_ejecutada', 'unique_together': {('tipo_trabajo_ejecutado', 'mano_de_obra')}},
        ),
        migrations.CreateModel(
            name='TipoTrabajoPartida',
            fields=[
                ('id_tipo_trabajo_partida', models.AutoField(primary_key=True, serialize=False)),
                ('mano_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_trabajo', to='core.manodeobra')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='core.tipotrabajo')),
            ],
            options={'db_table': 'tipo_trabajo_partida', 'unique_together': {('tipo_trabajo', 'mano_de_obra')}},
        ),
        migrations.DeleteModel(name='SuministroManoDeObra'),
    ]
