# Generated by Django 6.0 on 2026-05-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_actividad_alter_sst_actividad_liquidacionsuministro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sst',
            name='sst',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('almacen', 'mes', 'anio'), ('camion', 'mes', 'anio')},
        ),
    ]
