# Generated by Django 6.0 on 2026-05-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reestructura_suministro_mdo_recupero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sstencargado',
            name='rol',
        ),
    ]
