# Generated by Django 6.0 on 2026-05-20 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sstencargado_quitar_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionSuministro',
            fields=[
                ('id_liquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.suministro')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.tipotrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.usuario')),
            ],
            options={
                'db_table': 'liquidacion_suministro',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionPartida',
            fields=[
                ('id_liquidacion_partida', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mano_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.manodeobra')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='core.liquidacionsuministro')),
            ],
            options={
                'db_table': 'liquidacion_partida',
                'unique_together': {('liquidacion', 'mano_de_obra')},
            },
        ),
    ]
