# Generated by Django 6.0 on 2026-05-22 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tipotrabajomaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTrabajoMaterialProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Tipo trabajo material',
                'verbose_name_plural': 'Tipo trabajos materiales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.tipotrabajo',),
        ),
        migrations.RemoveField(
            model_name='tipotrabajomaterial',
            name='cantidad',
        ),
    ]
