# Generated by Django 6.0 on 2026-05-27 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_actividad_tipo_trabajo_y_suministro_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcamion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
