# Generated by Django 6.0 on 2026-06-18 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_stock_camion_cantidad_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoSST',
            fields=[
                ('id_plano', models.AutoField(primary_key=True, serialize=False)),
                ('sst_codigo', models.CharField(db_index=True, max_length=20)),
                ('elementos', models.JSONField(default=list)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='core.usuario')),
            ],
            options={
                'db_table': 'plano_sst',
                'unique_together': {('empresa', 'sst_codigo')},
            },
        ),
    ]
